apiVersion: skaffold/v2alpha1
kind: Config
build:
    artifacts:
    - image: cloud-native-go-helloworld-service
deploy:
    helm:
      releases:
        - name: cloud-native-go-helloworld-service
          chartPath: charts/cloud-native-go-helloworld-service
          wait: true
          setValues:
            imagePullPolicy: IfNotPresent
          values:
            image: cloud-native-go-helloworld-service
          imageStrategy:
            helm: {}
profiles:
- name: local
  activation:
    - kubeContext: docker-for-desktop
    - kubeContext: docker-desktop
  build:
    artifacts:
    - image: cloud-native-go-helloworld-service
    local:
      useBuildkit: true
  test:
  - image: cloud-native-go-helloworld-service
    structureTests:
      - './image-test/*'
