# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: 
  repository: cloud-native-go-helloworld-service
  tag: ""
imagePullPolicy: IfNotPresent

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 5

service:
  type: ClusterIP
  port: 3000

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpu: 80
  memory: 512Mi
  requests:

resources:
  requests:
    memory: "512Mi"
    cpu: "128m"
  limits:
    memory: "768Mi"
    cpu: "1024m"

nodeSelector: {}

tolerations: []

affinity: {}
